env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
globals:
  cordova: readonly
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
